#!/bin/bash -login
#PBS -l walltime=15:00:00,nodes=1:ppn=1,mem=20g
#PBS -q main
#PBS -M qingpeng@gmail.com
#PBS -m abe
#PBS -A ged-intel11

module load khmer
module load screed

cd $PBS_O_WORKDIR
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 AB.tr.fq.trimmed.ht AB.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 BB.tr.fq.trimmed.ht BB.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 BH.tr.fq.trimmed.ht BH.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 IB.tr.fq.trimmed.ht IB.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 IH.tr.fq.trimmed.ht IH.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 MB.tr.fq.trimmed.ht MB.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 MH.tr.fq.trimmed.ht MH.tr.fq.trimmed
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 5e9 PB.tr.fq.trimmed.ht PB.tr.fq.trimmed
